IVI-665 - Updating order sdk protos to match IVI protos and responses.
MythicalGames/ivi-sdk-proto pull request #12
Opened 2021-03-30 23:30 UTC by kwang-mythical

2021-03-31 00:34 UTC, keith-miller approved these changes
lgtm

2021-03-31 17:09 UTC, keith-miller commented
Let's not push this in until the SDK gets deployed to QA.

2021-03-31 20:29 UTC, keith-miller requested changes

2021-03-31 20:29 UTC, keith-miller commented on api/order/definition.proto
> +  repeated IssuedItem item_types = 1;
This should stay called `purchased_items`. Calling it `item_types` is confusing.

2021-03-31 20:29 UTC, keith-miller commented on api/order/definition.proto
> +      IssuedItems item_types = 7;
Same as above.

2021-03-31 20:29 UTC, keith-miller commented on api/order/definition.proto
> +    IssuedItems item_types = 10;
Same as above.

2021-03-31 20:29 UTC, keith-miller commented on api/order/definition.proto
>    string item_type_id = 3;
`item_type_id` needs to be `game_item_type_id` now.

2021-03-31 21:43 UTC, kwang-mythical commented on api/order/definition.proto
> +  repeated IssuedItem item_types = 1;
roger, we're gonna need a rename on IVI then

2021-03-31 21:47 UTC, kwang-mythical commented on api/order/definition.proto
>    string item_type_id = 3;
yeah, your changes should've covered this, rebasing branch for update.

2021-04-02 23:03 UTC, keith-miller approved these changes

2021-04-02 23:04 UTC, merged