IvI-2250 Add Uphold Support
MythicalGames/ivi-sdk-proto pull request #24
Opened 2021-09-24 19:48 UTC by erik-mythical

Not really sure about what this needs to look like so I decided to start the PR even though I'm still working on the implementation in ivi-engine.

2021-09-24 23:55 UTC, keith-miller requested changes
Just one question

2021-09-24 23:55 UTC, keith-miller commented on api/order/payment.proto
> +  UPHOLD = 6;
Why 6?

2021-09-25 14:46 UTC, erik-mythical commented on api/order/payment.proto
> +  UPHOLD = 6;
That is the ordinal in the platform-grpc enum of the same thing and I wasn't sure if we wanted to use the same ordinal here or not.

2021-09-25 17:31 UTC, kwang-mythical commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
are you starting only with the GET and working thru later to figure out what else you need or do you have the necessary calls figured out?

2021-09-25 19:37 UTC, erik-mythical commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
I'm not entirely sure what is needed in the SDK so I'm starting with the GET. I think the changes in this PR are what is needed to view the Uphold wallet data and make payments with an Uphold wallet.

2021-09-25 23:47 UTC, keith-miller commented on api/order/payment.proto
> +  UPHOLD = 6;
Nah, let's make it 3 please.

2021-09-25 23:49 UTC, keith-miller commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
I think we just need to support the game/web stores to allow users to use existing wallets/balances for payment. We don't need to add the functionality to create/update/delete. Users can go to their account page in marketplace to do that. Adding @sebastiano-mythical to confirm

2021-09-26 20:17 UTC, keith-miller approved these changes
lgtm

2021-09-26 23:38 UTC, sebastiano-mythical commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
I'll have an answer on this once the UI designs for the webstore are completed. They have an "account" page and the initial direction is to point them to the marketplace wallet page to link, so Get would be the only required command.
However I'll circle back once execs have approved the store UI flow.

2021-09-27 00:38 UTC, keith-miller commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
Alright, if it changes then that can be another task for later. For now we'll just focus on using wallets for payments.

2021-09-27 13:33 UTC, erik-mythical commented on api/wallet/rpc.proto
> +  rpc GetWalletUser(ivi.proto.api.wallet.GetWalletUserRequest) returns (ivi.proto.api.wallet.Wallet);
Sounds good. Thanks for the clarification.

2021-09-27 14:52 UTC, kwang-mythical approved these changes

2021-09-28 21:27 UTC, merged